
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: karaf-camel-amq
spec:
  type: standard
  plan: standard-unlimited
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
    exports:
    - kind: ConfigMap
      name: karaf-camel-amq-config
    cert:
      provider: openshift