apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: karaf-camel-amq.client
spec:
  username: user1
  authentication:
    type: password
    password: dGVzdA==
  authorization:
    - operations: ["send", "recv"]
      addresses: ["incomingOrders"]
